### ISSUE TITLE
配置完了生成的地址不对。

### ISSUE THREAD

**Issue by lefinite** [zWingz/picgo-plugin-github-plus#1]
配置如下图：
![image](https://user-images.githubusercontent.com/23370734/51448823-076c8b80-1d64-11e9-9c64-ea48e5b8ae3f.png)

生成的链接（无效的）：
https://raw.githubusercontent.com/Picture/20190121100813.png

我去仓库找到的图片真实链接：
https://raw.githubusercontent.com/lefinite/Picture/master/20190121100813.png

请问一下是哪里配置的不对还是什么原因，该怎么操作呢？

**Comment by zWingz** [comment]
我这边的问题，我晚些修复下

**Comment by love201314** [comment]
使用了自定义的域名生成图片地址不正确
![snipaste_2019-03-08_10-42-28](https://user-images.githubusercontent.com/25261316/54003969-ec789e00-418e-11e9-9803-3395bd72cfff.png)

生成的链接（无效的）：
[https://pic.kx520.com/picture/img/nature-21606.jpg](url)
有效的地址是：
[https://pic.kx520.com/img/nature-21606.jpg](url)

地址生成的链接应该是加上了仓库的名称
不知道是否是我配置的不正确

**Comment by zWingz** [comment]
你将CNAME直接重定向到该`repo`, 你在path中写入`../img`试试

**Comment by zWingz** [comment]
@love201314 好像不行, 我再看看

**Comment by love201314** [comment]
嗯，好， 我刚配了下， 也确实不行

**Comment by zWingz** [comment]
@love201314 我看你的`data.json`路径不对, 你配置`path`的时候都是配了`/img`或者`img/`吗 ? 你是windows吗

**Comment by love201314** [comment]
@zWingz 是的

**Comment by love201314** [comment]
@zWingz 我是直接把GitHub图床设置部分直接复制粘贴上去的

**Comment by zWingz** [comment]
@love201314 更新插件看看. fixed 0fd147cc3ad7d3b7568cd673fcd7c8f0d0ab4c4d

**Comment by love201314** [comment]
@zWingz 已经正常了， 万分感谢

**Comment by zWingz** [comment]
@love201314 有问题可以新开issues

**Comment by love201314** [comment]
@zWingz ok
