### ISSUE TITLE
期望开发一个新插件

### ISSUE THREAD

**Issue by luoxiao** [zWingz/picgo-plugin-github-plus#13]
嗨，能否开发一个支持gitee的插件？
gitee相对比github速度快很多，国内用户很多都希望有吧。
谢谢哈。

**Comment by zWingz** [comment]
我这边看看先

**Comment by luoxiao** [comment]
感谢，期待

**Comment by zWingz** [comment]
gitee好像不支持图片外链访问哦

**Comment by luoxiao** [comment]
作者你好，gitee可以支持pages的啊，文件都有外链的，哈哈。

**Comment by zWingz** [comment]
那我再研究下..

**Comment by luoxiao** [comment]
感谢

**Comment by zWingz** [comment]
gitee有`1m`文件限制
大于`1m`需要登录才能看. 所以大于`1m`的图片这样是无法外链

**Comment by zWingz** [comment]
![image](https://user-images.githubusercontent.com/13031838/59601386-64634680-9136-11e9-8eed-8c22e53a8ee7.png)
更新插件后可以使用

**Comment by luoxiao** [comment]
我就知道找对了人，太感谢了。我现在就试试。

**Comment by luoxiao** [comment]
你好，已经用上。测了下可以上传5MB 的gif文件。
谢谢作者，太完美了。

**Comment by zWingz** [comment]
可以上传, 但是不能展示吧

**Comment by luoxiao** [comment]
可以开通pages功能，就没这个限制了，哈哈。

**Comment by zWingz** [comment]
这样的吗..好
