### ISSUE TITLE
图片上传不成功

### ISSUE THREAD

**Issue by lefinite** [zWingz/picgo-plugin-github-plus#18]
![image](https://user-images.githubusercontent.com/23370734/70677461-2d778300-1cca-11ea-9e69-551d773a4e25.png)
如图所示，不管是从剪贴板上传，还是本地上传图片，都无法传成功。

**Comment by lefinite** [comment]
相同的配置，但是使用软件自带Github图床，能上传成功。

**Comment by zWingz** [comment]
能否截图看下配置, 看错误提示应该是token不正确
