### ISSUE TITLE
不能将图片上传到特定文件夹

### ISSUE THREAD

**Issue by dasnnj** [zWingz/picgo-plugin-github-plus#2]
picgo本身自带的github图床工具，只要设置了文件路径就可以自动创建文件夹，并上传到里面。但是githubplus只能将路径名重命名为文件前缀，而不能上传到文件夹中。

**Comment by zWingz** [comment]
有个配置项叫 `path`, 你可以试试

**Comment by dasnnj** [comment]
> 有个配置项叫 `path`, 你可以试试

这个选项的话我设置的如` img/'但是好像仅仅在文件名字上做了改变

**Comment by zWingz** [comment]
说下使用的版本?
方便的话给我截个图看看实际情况

**Comment by dasnnj** [comment]
> 说下使用的版本?
> 方便的话给我截个图看看实际情况

可能是我操作有错误，在另一台pc上是ok的。晚上我需要在检查一下

**Comment by zWingz** [comment]
两个系统不一致吗?

**Comment by dasnnj** [comment]
可能是个bug
在一台电脑上是正常的，而另一台是有问题的 **我对照检查了几遍，配置是完全一样**
有问题的会出现这个情况
![](https://newblog.dasnnj.cn/imagesbed/images/example.png)
anyway这台有问题的，我卸载插件后又重装一边就正常了。

**Comment by dasnnj** [comment]
picgo版本2.0.5
plus版本1.1.2
找到了原因：
- 图片名字中有中文就会找不到path，并且将文件重命名为path+name
- 图片名字无中文时能正常将图片上传至指定path下

**Comment by zWingz** [comment]
是windows吗 @dasnnj

**Comment by zWingz** [comment]
@dasnnj 后续会发版本修复

**Comment by zWingz** [comment]
close 8b86cd5ee97b49dec908fc95ea413df232405b7a

**Comment by zWingz** [comment]
更新插件应该解决了 @dasnnj

**Comment by lenvo222** [comment]
> 更新插件应该解决了 @dasnnj

子文件夹怎么创建
