### ISSUE TITLE
执行pull或者sync之后，相册里不显示

### ISSUE THREAD

**Issue by yf-9186** [zWingz/picgo-plugin-github-plus#21]
使用Molunerfinn的PicGo 2.2.0，安装的插件。执行pull origin或者sync origin之后，通过vs-picgo上传到github的图片并不会马上显示到相册里，data.json里是有这部分图片信息了。然后重启picgo之后，这部分图片才显示到相册中。
能否让sync origin或pull origin后，这部分图片不需要重启在相册中马上显示。

**Comment by zWingz** [comment]
picgo好像没提供接口刷新
