### ISSUE TITLE
执行pull后，将data.json中由githubplus上传的图片数据都清空了。

### ISSUE THREAD

**Issue by yf-9186** [zWingz/picgo-plugin-github-plus#22]
你好，我用githubplus上传图片的时候设置了不同的path。然后当我在某一个path执行pull以后，githubplus清空了data.json中其他path的图片数据。建议修改为只删除这一个path下的图片数据；而保留，其他path的图片数据。

**Comment by zWingz** [comment]
这一部分是picgo的底层实现, 我没法控制. 如果可以建议使用 [https://github.com/zWingz/Hyrule](https://github.com/zWingz/Hyrule) 更方便

**Comment by ttimasdf** [comment]
现在这里只获取了Github仓库中 `path` 参数对应的一级目录下的文件，改成从根目录递归获取文件信息，再用过滤器把图片筛出来应该就可以了，这样外面的API也不用变。

https://github.com/zWingz/picgo-plugin-github-plus/blob/d86fb3b89f5a2fc9d7da2dd8878db94a26e03488/lib/octokit.ts#L53-L65

**Comment by zWingz** [comment]
目前picgo不支持path切换，如果按照你所说的，是可以把所有图片都加载出来，但是新增的图片还是只能在对应的path下，这样就跟repo的目录结构不一致。而且我直接存在根目录不就能解决这个问题了吗？
