### ISSUE TITLE
支持jsdelivr提供的CDN服务

### ISSUE THREAD

**Issue by yansheng836** [zWingz/picgo-plugin-github-plus#25]
【功能】支持jsdelivr提供的CDN服务。
【说明】
1. GitHub服务器在国外，国内访问有所限制，进程会导致图片或者文件等刷不出来。
2. [jsdelivr](https://www.jsdelivr.com/?docs=gh) 免费为github 公开仓库（文件）提供CDN服务，感觉比github快很多。
3. 而且配置很简单，如：photos仓库下img文件夹内某文件路径为： "yansheng836/photos/img/（古风美人）绘师：喵喵九季.jpeg" 的CDN网址为：<https://cdn.jsdelivr.net/gh/yansheng836/photos/img/（古风美人）绘师：喵喵九季.jpeg> 。
4. GitHub图床支持自定义域名，但是好型不太支持jsdelivr格式的，如我试了下发现 `https://cdn.jsdelivr.net/gh` 可以（然而上传后路径变成这样：<https://cdn.jsdelivr.net/gh/img/5c9dda67deb87.jpg> ，这样是访问不了对应图片的），但是 `https://cdn.jsdelivr.net/gh/yansheng836/photos` 却不可以，希望GitHub图床能够支持jsdelivr风格的自定义域名。

**Comment by zWingz** [comment]
你把`customUrl`设为 `https://cdn.jsdelivr.net/gh/yansheng836/photos`不就好了吗?

**Comment by yansheng836** [comment]
额，已解决该问题，忘记关issues了。我的问题好像是小概率事件，配置是对的，第一天不行，第二天再次尝试就可以了。
