### ISSUE TITLE
picgo 2.3.0 beta5y以后无法pull origin

### ISSUE THREAD

**Issue by rayaldeng** [zWingz/picgo-plugin-github-plus#36]
**现象**：一台电脑安装了2.2.2可以正常sync和pull，另一台安装了2.3.0 beta6，始终pull origin fail， 提示“Cannot read property 'filter' of undefined”

**可能的原因**：看了一下picgo的[2.3.0 beta5 release日志](https://github.com/Molunerfinn/PicGo/releases/tag/v2.3.0-beta.5)，提到“PicGo-Core 升级到 v1.4.19， 从这个版本起，插件无法修改相册列表，只读不可写，避免一些插件对相册列表的误操作导致越删越多的情况。”

这是说以后就无法同步了？

**Comment by zWingz** [comment]
@rayaldeng 目前是的. 跟作者沟通过后续会有调整...我到时再跟进下吧

**Comment by JoJoJotarou** [comment]
@zWingz [picgo-core 1.4.24](https://github.com/PicGo/PicGo-Core/blob/dev/CHANGELOG.md#tada-1424-2021-08-01) 取消了对uploaded修改的限制

我基于picgo master分支查看代码，发现picgo使用[GalleryDB](https://github.com/Molunerfinn/PicGo/blob/f3ec0cb4be63024123a12440cc597f1469a340a1/src/main/apis/app/uploader/apis.ts#L26)来存储上传后的图片信息，存储位置是[picgo.db](https://github.com/Molunerfinn/PicGo/blob/f3ec0cb4be63024123a12440cc597f1469a340a1/src/main/apis/core/datastore/dbChecker.ts#L123)，基于[picgo/store](https://github.com/PicGo/store)

看上去是好像是可以fix pull origin 这项功能

**Comment by zWingz** [comment]
..我已经好久没关注这个项目了 @JoJoJotarou 最近可能也没啥时间搞

**Comment by zWingz** [comment]
一不小心就发现这么多issues..

**Comment by zWingz** [comment]
@JoJoJotarou 试了下目前又可以了...

**Comment by zWingz** [comment]
![image](https://user-images.githubusercontent.com/13031838/159467233-a671e076-c50f-46af-bb90-3bab327e5151.png)
如果用心的api的话没办法直接覆盖本地的图片..
但我试了下, 更新uploaded的话, 一定程度也能实现同步
