### ISSUE TITLE
能否把token设计成隐藏且不可复制的形式？

### ISSUE THREAD

**Issue by Jingzhenzxz** [zWingz/picgo-plugin-github-plus#39]
在githubplus的设置中，token是明文且可复制的，能否设计成隐藏且不可复制的形式？

![image](https://user-images.githubusercontent.com/47069834/130573060-ec1c6f4c-617b-46df-9c20-6a46df697a8b.png)

**Comment by zWingz** [comment]
好像不行啊..除非picgo支持oauth..
