### ISSUE TITLE
2.3.0更新插件后上传失败

### ISSUE THREAD

**Issue by A-little-bit-of-data** [zWingz/picgo-plugin-github-plus#44]
用的最新版的软件跟插件，但是上传图片的时候路径上会多出一个路劲，麻烦看看是怎么回事？这个content没配置，但是自己跳出来了，应该就是i这个路径导致失败的吧
![image](https://user-images.githubusercontent.com/31812278/147050108-14a2002c-39c2-40f8-bfb4-82ac584d353e.png)

**Comment by zWingz** [comment]
是不是gitee api改了呀...

**Comment by zWingz** [comment]
`https://gitee.com/api/v5/repos/{owner}/{repo}/contents/{path}` 这是gitee的api, 是没问题的, 你的错误信息是网络问题
