### ISSUE TITLE
No token in url

### ISSUE THREAD

**Issue by ViGeng** [zWingz/picgo-plugin-github-plus#5]
I use githubPlus:
"(url)"

I use GitHub图床：
"(url?token=AeXKna1KlC8BHmvrZ7JrUSTCMAPuibxQ***)"

There is no token of my pic, do you know about this?
Thanks.

**Comment by zWingz** [comment]
there is not `url` in `config`
can i have more details about it ?

**Comment by ViGeng** [comment]
for example:
I upload a pic to github then get the generated url of this pic : 
`![](https://raw.githubusercontent.com/ViGeng/pics/master/201904/20190413212946.png)`
As shown url above, there is no token in Url. So it doesn't work. I think a valid pic url should have a token like this:
`![](https://raw.githubusercontent.com/ViGeng/pics/master/201904/20190413213607.png?token=AeXKnc-ilnIYpvtC6MJ0mKDlwyj66OiHks5cseYEwA%3D%3D)`
There is no business about config. Wish you know what I mean.
Thanks for your efforts to this awesome plugin!

**Comment by zWingz** [comment]
your `repo` is private
so it need a token to access
but the token would be refresh
so, `private repo` can't access as a public repo  
you have to set `repo` public

**Comment by ViGeng** [comment]
I see...
Thank you.
