### ISSUE TITLE
【feture report】同步data.json文件内容不对

### ISSUE THREAD

**Issue by cooper1x** [zWingz/picgo-plugin-github-plus#6]
同步到github后结果是这个，和预想的完整图床和相册配置不太一样
```
{"data":[],"lastSync":"2019-04-21 11:07:16"}
```
其实同步配置我用过vscode的一个插件，可以同步到私有的github gist上，没有必要新建一个repo。
可以参照下这个插件：
[Settings Sync - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)

**Comment by zWingz** [comment]
gist必须要梯子,而且很慢, 也不容易管理
图片一多的话. 还是需要clone下来管理的

**Comment by cooper1x** [comment]
原来是这样，gist没有觉得，一直都开着梯子……
只是对我来说，只需要能同步图床配置和相册图片URL就可以了，图片传github这个需求我暂时还没有。
换电脑或者win重装系统，同步picgo的软件配置我认为是更重要的功能。
之前重装，我都是用everything搜的picgo的配置文件，找了一会儿才发现这个data.json
`C:\Users\xxx\AppData\Roaming\picgo`在下面。

**Comment by zWingz** [comment]
所以这不算是bug吧?

**Comment by cooper1x** [comment]
emmmmm，我改一下，算是一个功能建议吧

**Comment by zWingz** [comment]
但其实我这个插件只是用来同步图片, 而不是用来同步配置
而且配置中包含github 的token, 是不允许把token上传到github上面的
