### ISSUE TITLE
插件怎么配置

### ISSUE THREAD

**Issue by lenvo222** [zWingz/picgo-plugin-github-plus#7]
插件怎么配置啊,上传不了啊,谢谢大佬

**Comment by zWingz** [comment]
给我看下你的配置信息

**Comment by zWingz** [comment]
![image](https://user-images.githubusercontent.com/13031838/57566062-a7752000-73fa-11e9-99c1-e3a0562bc41d.png)
自己替换就好了

**Comment by lenvo222** [comment]
![Snipaste_2019-05-11_15-01-07](https://user-images.githubusercontent.com/39437437/57566316-a98cae00-73fd-11e9-97ea-4c51372915ed.png)

**Comment by zWingz** [comment]
@lenvo222 点左边的githubPlus进行配置

**Comment by lenvo222** [comment]
![image](https://user-images.githubusercontent.com/39437437/57566348-f6708480-73fd-11e9-959d-dfa107a37e3c.png)
这样设置了,但还是上传失败了

**Comment by lenvo222** [comment]
![image](https://user-images.githubusercontent.com/39437437/57566369-3cc5e380-73fe-11e9-996d-7d466aa16e6e.png)

**Comment by lenvo222** [comment]
不错啊,大大 ,搞定了

**Comment by zWingz** [comment]
好

**Comment by lenvo222** [comment]
token 不能放在github 仓库里面,否则会让token失效的  
结帖了
