### ISSUE TITLE
不能上传文件名相同的文件吗

### ISSUE THREAD

**Issue by lenvo222** [zWingz/picgo-plugin-github-plus#8]

**Comment by lenvo222** [comment]
还有个问题, 子文件夹怎么创建, 谢谢大佬

**Comment by zWingz** [comment]
我没有做文件名重复限制, 如果有那应该是`app`内置限制了.
当然, 最好不要重复

关于子文件夹, 在`path`选项设置后, 上传的图片都会在该路径下

**Comment by lenvo222** [comment]
子文件夹修改这一处吗





------------------ 原始邮件 ------------------
发件人: "zWing"<notifications@github.com>; 
发送时间: 2019年5月11日(星期六) 下午4:08
收件人: "zWingz/picgo-plugin-github-plus"<picgo-plugin-github-plus@noreply.github.com>; 
抄送: "太阳"<897057246@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zWingz/picgo-plugin-github-plus] 不能上传文件名相同的文件吗 (#8)




我没有做文件名重复限制, 如果有那应该是app内置限制了.
 当然, 最好不要重复
 
关于子文件夹, 在path选项设置后, 上传的图片都会在该路径下

**Comment by lenvo222** [comment]
子文件夹修改这一处吗
![image](https://user-images.githubusercontent.com/39437437/57567149-91ba2780-7407-11e9-95d8-b3270a9984e5.png)

**Comment by zWingz** [comment]
对的

**Comment by lenvo222** [comment]
大佬,在国外吗

**Comment by zWingz** [comment]
不在

**Comment by lenvo222** [comment]
还是不会创建子文件夹, 😂

**Comment by zWingz** [comment]
![image](https://user-images.githubusercontent.com/13031838/57567214-7dc2f580-7408-11e9-8d8b-a5b4ebe6ca23.png)
可以啊

**Comment by lenvo222** [comment]
必须写成这个名字吗

**Comment by lenvo222** [comment]
![](https://raw.githubusercontent.com/lenvo222/PicgoData/master/20190511162230.png)

**Comment by lenvo222** [comment]
还是没出来
![image](https://user-images.githubusercontent.com/39437437/57567289-60425b80-7409-11e9-835c-bff0f11a1e23.png)

**Comment by zWingz** [comment]
任何`path`都可以. 有没有错误提示

**Comment by lenvo222** [comment]
没有啊,可以上传,但是我没有文件夹

**Comment by zWingz** [comment]
重新启动app

**Comment by lenvo222** [comment]
是的, 完美解决

**Comment by zWingz** [comment]
更新插件了
修改配置后可以不用重启

**Comment by lenvo222** [comment]
感觉这个删除不利索, 有时候,picgo 删除了,github上还没删除

**Comment by zWingz** [comment]
由于`picgo`没有提供相关`hook`
无法做到同步删除

**Comment by lenvo222** [comment]
> 更新插件了
> 修改配置后可以不用重启

感觉这个删除不利索, 有时候,picgo 删除了,github上还没删除

**Comment by lenvo222** [comment]
plus 不是已经可以同步删除了吗

**Comment by zWingz** [comment]
我指的同步是
github删除后本地才删除
目前本地和github都是分开

**Comment by lenvo222** [comment]
![image](https://user-images.githubusercontent.com/39437437/57567548-61758780-740d-11e9-9713-1c3373597a19.png)

**Comment by zWingz** [comment]
要注意该图片是否在当前设置的`path`内, 否则会失败

**Comment by lenvo222** [comment]
在多问下, 开发这款插件 ,前提我需要了解哪方面的编程技巧,    或者我需要去看那些资料

**Comment by zWingz** [comment]
javascript

**Comment by lenvo222** [comment]
虽然他现在还不是很完美, 但我想让他走的更远

**Comment by lenvo222** [comment]
能做到现在已经很棒了,感谢您的分享👍

**Comment by zWingz** [comment]
这个主要看`picgo`能提供`api`到什么层度.

**Comment by lenvo222** [comment]
也就是说, `picgo` 要做很多工作了

**Comment by zWingz** [comment]
是的

**Comment by zWingz** [comment]
是的
