### ISSUE TITLE
删除图片失败

### ISSUE THREAD

**Issue by lizhuangs** [zWingz/picgo-plugin-github-plus#9]
环境win8.1。path配置的是`images/`  ，提示删除成功，然后提示githubplus删除失败xxx个。
测试发现，只要删除path改为空，就可以正常删除。

**Comment by zWingz** [comment]
你要确定你本地图片实际存储是在对应的path才能删，比如说你在a/上传了10张，然后将path改成b/，这是之前的图片还是存在，但是你无法删除，只能将path改成a/

**Comment by lizhuangs** [comment]
我把path改为a/，然后上传一张图，在github查看也有图片a/下面，然后我不改path直接删除就是报这个错。

**Comment by zWingz** [comment]
我测试了没什么问题喔.
方便截图下配置吗

**Comment by lizhuangs** [comment]
```
"picgo.picBed.current": "github",
    "picgo.picBed.github.token": "xxx",
    "picgo.picBed.github.repo": "lizhuangs/blog-images",
    "picgo.picBed.github.branch": "master",
    "picgo.customOutputFormat": "<img src=\"${url}\" alt=\"${uploadedName}\" style=\"height:200px\" />",
    "picgo.dataPath": "C:\\Users\\Administrator\\AppData\\Roaming\\picgo\\data.json",
    "picgo.picBed.github.customUrl": "http://xxx.gitee.io/blog-images",
```

**Comment by zWingz** [comment]
这个是picgo自带的`github`图床, 不是我这边的呀

**Comment by lizhuangs** [comment]
呃，复制错了，但是配置是一样的。

**Comment by zWingz** [comment]
每次修改完`config`都要重启`app`的.
你可以试下重启后先`pull`一遍, 然后再删除
如果再失败的话, 留意下失败信息

**Comment by lizhuangs** [comment]
失败有日志没有。现在只有提示：删除失败，删除失败1个。

**Comment by zWingz** [comment]
更新下插件
然后重试下你的步骤
打开app的`log`文件, 把错误发来看看

**Comment by zWingz** [comment]
![image](https://user-images.githubusercontent.com/13031838/58685895-ce969000-83af-11e9-8af3-99abbcc510aa.png)

**Comment by lizhuangs** [comment]
比较尴尬，删除失败里面没有日志。。上传成功倒是有日志。。。我明天有空源码安装看一下吧。

**Comment by lizhuangs** [comment]
```
2019-06-06 01:34:02 [PicGo ERROR] {"owner":"lizhuangs","repo":"blog-images","branch":"master","path":"images/","token":"xxx","customUrl":""}
2019-06-06 01:34:03 [PicGo ERROR] 删除文件出错
2019-06-06 01:34:03 [PicGo ERROR] {"extname":"jpg","fileName":"Screenshot_2015-01-07-18-58-01.jpg","id":"9f7ef376431c5a2a629aca76d23d87c972f0991f", 
 "imgUrl":"https://raw.githubusercontent.com/lizhuangs/blog-images/master/images/Screenshot_2015-01-07-18-58-01.jpg",  
"sha":"9f7ef376431c5a2a629aca76d23d87c972f0991f","type":"githubPlus"}
2019-06-06 01:34:03 [PicGo ERROR] HttpError: Not Found
------Error Stack Begin------
HttpError: Not Found
    at response.text.then.message (C:\Users\Administrator\AppData\Roaming\picgo\picgo-plugin-github-plus\node_modules\@octokit\request\dist-node\index.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-------Error Stack End-------
```

我用源码安装，然后加了点日志打印出来，错误大约是这样的。

**Comment by lizhuangs** [comment]
测试了一下，当access_token、或sha等参数不传或错误时，会报这个错。但是我复制到postman中是可以成功执行的。看起来和octokit有关。

**Comment by lizhuangs** [comment]
我直接修改ts编译后的js，加上jquery调用原生api成功了。但是我不确定是octokit的问题，还是你使用的octokit传参有问题。因为我抓包octokit只能看到是加密的tcp请求，而不是https请求，所以。。。

**Comment by lizhuangs** [comment]
我刚才测试无意中看到`join(path, img.fileName)`打印出来的结果为xxx\xxx，改为`path + img.fileName`就好了，不过我的path配置的是'images/'，如果配置的是'images'，这里还需要加上/。所以需要判断一下。
我刚才fork了分支提交了合并请求。

**Comment by zWingz** [comment]
更新下应该ok了

**Comment by yikexiaoyao** [comment]
图片删除后重启软件出现空位，删不掉，每次重启都会出现
![Snipaste_2022-06-13_15-03-06](https://user-images.githubusercontent.com/36374114/173297904-6a682764-2315-42d8-937c-2dde42a0aafd.png)
